In [ ]:
#ex1
number=[]
for x in range(2000, 3201):
    if (x%7==0) and (x%5>0):
        number.append(str(x))
for x in number :
  print(number)

In [ ]:
#exfact
n= int(input("Enter a number: "))
f=1
for x in range(1,n+1):
  f=x*f
  print(f)

In [ ]:
#ex3
n = int(input("Type a number: "))

Dict = {}
for i in range(1,n+1):
    Dict[i] = i*i

print(Dict)

In [ ]:
#ex4
ch=str(input("donner la chaine="))
n=int(input("donner la postion=" ))
list1=list(ch)
if n>=0 and n<=len(ch)-1 :
  del list1[n]
  ch="".join(list1)
  print(ch)

In [ ]:
#ex5
import numpy as np
b=np.array([[1,2],[3,4]])
list1=list(b)
print(list1)

In [1]:
#ex6
import numpy as np
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("\nOriginal array1:")
print(x)
print("\nOriginal array1:")
print(y)
print("\nCovariance matrix of the said arrays:\n",np.cov(x, y))


Original array1:
[0 1 2]

Original array1:
[2 1 0]

Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]


In [ ]:
#ex7
import math
d=int(input("donner la valuer="))
c=50
h=30
while(d!=0) :
  q=math.sqrt((2 * c * d)/h)
  print(int(q))
  d=int(input("donner autre valuer="))